### PR TITLE
Replaced NgInjectors with Inline Array Annotation

### PR DESCRIPTION
**Pull request by MaxSassen**
Should fix issue:
https://github.com/abandon-ship/ng-feature-toggle/issues/5

### CODE REVIEW

**Comment by daanvanhulst** [comment]
Still has to be tested

**Comment by haiyanghe** [comment]
Hey, any updates on this issue?

**Comment by MaxSassen** [comment]
@haiyanghe I'm not sure, still waiting that this pull request is acccepted. Will try to contact the other developers.

**Comment by daanvanhulst** [comment]
@haiyanghe I reviewed the code and it looks good, but I have not been able to test it because I've been really busy with work these past months. I've merge it to master so you can test it yourself. Please let me know if this fixes the issue.

**Comment by blasky** [comment]
Was this ever tested and released? I'd like to use this package, but the 1.0.1 release in npm won't run without a "cannot be invoked in strict mode" error...?

**Comment by daanvanhulst** [comment]
@blasky I think something went wrong with publishing it to npm. The latest version I have published (1.0.4) is compatible with 'ng-strict-di'.

**Pull request merged**
